import type { Thread, Issue, Announcement, Ward, User } from "./types";

export const MOCK_USER: User = {
  uid: "user-resident-1",
  role: "RESIDENT",
  accountName: "Jane Doe",
  createdAt: new Date("2025-01-15"),
};

export const MOCK_WARDS: Ward[] = [
  {
    wardId: "ward-7",
    wardName: "Ward 7",
    repUid: "rep-1",
    wardRepEmail: "rep@ward7.gov",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    wardId: "ward-1",
    wardName: "Ward 1",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-02-01"),
  },
];

export const MOCK_THREADS: Thread[] = [
  {
    threadId: "thread-potholes",
    wardId: "ward-7",
    cityId: "markham",
    title: "Potholes on Main St",
    aiSummary:
      "Residents have reported multiple potholes along Main Street, particularly near the intersection with Oak Ave. Several vehicles have sustained damage. The surface deteriorates further after rain.",
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-10"),
    lastActivityAt: new Date("2025-02-10"),
    issueCount: 12,
    upvoteCount: 34,
    upvoteUids: ["u1", "u2"],
    issueIds: ["issue-1", "issue-2", "issue-3"],
  },
  {
    threadId: "thread-streetlights",
    wardId: "ward-7",
    cityId: "markham",
    title: "Streetlights not working near park",
    aiSummary:
      "Multiple streetlights are out near Riverside Park, creating safety concerns for evening pedestrians and cyclists. Reports indicate the issue has persisted for several weeks.",
    createdAt: new Date("2025-02-05"),
    updatedAt: new Date("2025-02-12"),
    lastActivityAt: new Date("2025-02-12"),
    issueCount: 7,
    upvoteCount: 21,
    upvoteUids: ["u1"],
    issueIds: ["issue-4", "issue-5"],
  },
  {
    threadId: "thread-garbage",
    wardId: "ward-7",
    cityId: "markham",
    title: "Garbage pickup delays",
    aiSummary:
      "Inconsistent garbage and recycling pickup schedules affecting several blocks. Bins left overflowing for days in some areas.",
    createdAt: new Date("2025-02-08"),
    updatedAt: new Date("2025-02-09"),
    lastActivityAt: new Date("2025-02-09"),
    issueCount: 5,
    upvoteCount: 18,
    upvoteUids: [],
    issueIds: ["issue-6"],
  },
  {
    threadId: "thread-noise",
    wardId: "ward-7",
    cityId: "markham",
    title: "Construction noise complaints",
    aiSummary:
      "Early morning construction noise from the new development site disturbing residents. Work sometimes starts before 7am on weekdays.",
    createdAt: new Date("2025-02-11"),
    updatedAt: new Date("2025-02-11"),
    lastActivityAt: new Date("2025-02-11"),
    issueCount: 3,
    upvoteCount: 8,
    upvoteUids: [],
    issueIds: ["issue-7"],
  },
  {
    threadId: "thread-sidewalk",
    wardId: "ward-7",
    cityId: "markham",
    title: "Cracked sidewalk hazards",
    aiSummary:
      "Uneven and cracked sidewalks posing trip hazards, especially for seniors and those with mobility aids. Several near-falls reported.",
    createdAt: new Date("2025-02-02"),
    updatedAt: new Date("2025-02-07"),
    lastActivityAt: new Date("2025-02-07"),
    issueCount: 9,
    upvoteCount: 42,
    upvoteUids: ["u1", "u2", "u3"],
    issueIds: ["issue-8", "issue-9", "issue-10"],
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    issueId: "issue-1",
    wardId: "ward-7",
    threadIds: ["thread-potholes"],
    text: "Large pothole right at the Main St and Oak Ave intersection. Almost lost a tire yesterday.",
    createdAt: new Date("2025-02-01T10:00:00"),
    authorUid: "u1",
    publicIdentityMode: "ANON",
    publicDisplayName: "Anonymous Samaritan",
    upvoteCount: 12,
    upvoteUids: ["u1", "u2"],
  },
  {
    issueId: "issue-2",
    wardId: "ward-7",
    threadIds: ["thread-potholes"],
    text: "Multiple potholes have appeared after the last storm. The road surface is really bad now.",
    createdAt: new Date("2025-02-03T14:30:00"),
    authorUid: "u2",
    publicIdentityMode: "PUBLIC",
    publicDisplayName: "John Smith",
    upvoteCount: 15,
    upvoteUids: ["u1", "u2", "u3"],
  },
  {
    issueId: "issue-3",
    wardId: "ward-7",
    threadIds: ["thread-potholes"],
    text: "The pothole near the bus stop has gotten worse. Dangerous for cyclists.",
    imageUrl: "https://placehold.co/400x200/e5e7eb/6b7280?text=Issue+Image",
    createdAt: new Date("2025-02-05T09:15:00"),
    authorUid: "u3",
    publicIdentityMode: "ANON",
    publicDisplayName: "Anonymous Samaritan",
    upvoteCount: 7,
    upvoteUids: ["u1"],
  },
  {
    issueId: "issue-4",
    wardId: "ward-7",
    threadIds: ["thread-streetlights"],
    text: "Three streetlights have been out on the path to Riverside Park for over a month. Very dark at night.",
    createdAt: new Date("2025-02-05T18:00:00"),
    authorUid: "u4",
    publicIdentityMode: "PUBLIC",
    publicDisplayName: "Maria Garcia",
    upvoteCount: 11,
    upvoteUids: ["u1", "u4"],
  },
  {
    issueId: "issue-5",
    wardId: "ward-7",
    threadIds: ["thread-streetlights"],
    text: "Walking home from the park last night was scary. Need those lights fixed ASAP.",
    createdAt: new Date("2025-02-10T20:30:00"),
    authorUid: "u5",
    publicIdentityMode: "ANON",
    publicDisplayName: "Anonymous Samaritan",
    upvoteCount: 10,
    upvoteUids: ["u1"],
  },
  {
    issueId: "issue-6",
    wardId: "ward-7",
    threadIds: ["thread-garbage"],
    text: "Recycling wasn't picked up last week. Bins are overflowing.",
    createdAt: new Date("2025-02-08T08:00:00"),
    authorUid: "u6",
    publicIdentityMode: "PUBLIC",
    publicDisplayName: "Alex Chen",
    upvoteCount: 18,
    upvoteUids: ["u1", "u2", "u6"],
  },
  {
    issueId: "issue-7",
    wardId: "ward-7",
    threadIds: ["thread-noise"],
    text: "Construction started at 6am again this morning. Impossible to sleep.",
    createdAt: new Date("2025-02-11T07:30:00"),
    authorUid: "u7",
    publicIdentityMode: "ANON",
    publicDisplayName: "Anonymous Samaritan",
    upvoteCount: 8,
    upvoteUids: ["u1"],
  },
  {
    issueId: "issue-8",
    wardId: "ward-7",
    threadIds: ["thread-sidewalk"],
    text: "The sidewalk outside 123 Elm St is severely cracked. My mother uses a walker and almost fell.",
    createdAt: new Date("2025-02-02T11:00:00"),
    authorUid: "u8",
    publicIdentityMode: "PUBLIC",
    publicDisplayName: "Sarah Lee",
    upvoteCount: 25,
    upvoteUids: ["u1", "u2", "u3", "u8"],
  },
  {
    issueId: "issue-9",
    wardId: "ward-7",
    threadIds: ["thread-sidewalk"],
    text: "Multiple cracks on Maple Ave between 4th and 5th. Needs repair before someone gets hurt.",
    createdAt: new Date("2025-02-04T15:45:00"),
    authorUid: "u9",
    publicIdentityMode: "ANON",
    publicDisplayName: "Anonymous Samaritan",
    upvoteCount: 12,
    upvoteUids: ["u1", "u9"],
  },
  {
    issueId: "issue-10",
    wardId: "ward-7",
    threadIds: ["thread-sidewalk"],
    text: "Uneven pavement near the school. Kids running could easily trip.",
    createdAt: new Date("2025-02-07T08:20:00"),
    authorUid: "u10",
    publicIdentityMode: "PUBLIC",
    publicDisplayName: "Mike Johnson",
    upvoteCount: 5,
    upvoteUids: [],
  },
];

export const MOCK_ANNOUNCEMENTS: Record<string, Announcement[]> = {
  "thread-potholes": [
    {
      announcementId: "ann-1",
      repUid: "rep-1",
      text: "Update: We've submitted a repair request to Public Works. Pothole filling is scheduled for the week of Feb 17. Thank you for your patience.",
      createdAt: new Date("2025-02-08T16:00:00"),
    },
  ],
  "thread-streetlights": [
    {
      announcementId: "ann-2",
      repUid: "rep-1",
      text: "The utility company has been notified. Streetlight repairs are in the queue. Expected completion: end of February.",
      createdAt: new Date("2025-02-11T10:00:00"),
    },
  ],
};
